name: SSTNotebooks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - xarray
  - requests
  - cdsapi
  - geopandas
  - rioxarray
  - cartopy
  - shapely
  - pandas
  - matplotlib
  - pip
  - pip:
      - futures